const fs = require('fs');

const questions = [
  {
    "testId": "java-test-01",
    "question": "What is the entry point of a Java program?",
    "options": [
      "public static void main(String[] args)",
      "public void main(String[] args)",
      "static public void main(String[] args)",
      "Both A and C"
    ],
    "correctOption": 3,
    "explanation": "The main method must be public, static, void, and accept String[] args. Both A and C are valid signatures."
  },
  {
    "testId": "java-test-01",
    "question": "What does JVM stand for?",
    "options": [
      "Java Virtual Machine",
      "Java Variable Manager",
      "Java Version Manager",
      "Java Visual Machine"
    ],
    "correctOption": 0,
    "explanation": "JVM stands for Java Virtual Machine, which interprets Java bytecode and provides a runtime environment."
  },
  {
    "testId": "java-test-01",
    "question": "Which of the following is NOT a Java keyword?",
    "options": ["static", "final", "enum", "global"],
    "correctOption": 3,
    "explanation": "'global' is not a Java keyword. Keywords include static, final, enum, and many others."
  },
  {
    "testId": "java-test-01",
    "question": "What is the size of an `int` in Java?",
    "options": ["8 bits", "16 bits", "32 bits", "64 bits"],
    "correctOption": 2,
    "explanation": "In Java, an `int` is a 32-bit signed integer, ranging from -2^31 to 2^31-1."
  },
  {
    "testId": "java-test-01",
    "question": "What is the default value of a `boolean` in Java?",
    "options": ["true", "false", "null", "0"],
    "correctOption": 1,
    "explanation": "The default value of a boolean is 'false'. For objects, it's null; for numeric types, it's 0."
  },
  {
    "testId": "java-test-01",
    "question": "Which of the following is a valid Java identifier?",
    "options": ["2var", "var-2", "_var2", "var 2"],
    "correctOption": 2,
    "explanation": "Java identifiers can start with a letter, underscore (_), or dollar sign ($). They cannot start with a digit or contain spaces."
  },
  {
    "testId": "java-test-01",
    "question": "What is the output of `System.out.println(10 / 4)`?",
    "options": ["2.5", "2", "3", "2.0"],
    "correctOption": 1,
    "explanation": "In Java, integer division truncates the decimal part. 10 / 4 = 2 (remainder ignored)."
  },
  {
    "testId": "java-test-01",
    "question": "Which package is automatically imported in every Java file?",
    "options": ["java.lang", "java.util", "java.io", "java.math"],
    "correctOption": 0,
    "explanation": "The `java.lang` package is automatically imported. Classes like String, System, and Math are in this package."
  },
  {
    "testId": "java-test-01",
    "question": "What is a Java bytecode?",
    "options": [
      "The intermediate code generated by the Java compiler",
      "The source code written by the developer",
      "The machine code executed by the CPU",
      "A type of Java comment"
    ],
    "correctOption": 0,
    "explanation": "Java source code is compiled to bytecode (.class files), which is then executed by the JVM."
  },
  {
    "testId": "java-test-01",
    "question": "Which of the following is NOT a primitive data type in Java?",
    "options": ["int", "float", "String", "boolean"],
    "correctOption": 2,
    "explanation": "String is a reference (non-primitive) data type. Primitive types include byte, short, int, long, float, double, char, and boolean."
  },
  {
    "testId": "java-test-01",
    "question": "What is the purpose of the `final` keyword on a variable?",
    "options": [
      "The variable cannot be reassigned",
      "The variable can be changed at any time",
      "The variable is static",
      "The variable is private"
    ],
    "correctOption": 0,
    "explanation": "A final variable is a constant that cannot be reassigned after initialization."
  },
  {
    "testId": "java-test-01",
    "question": "What is the output of `System.out.println(2 + \"2\")`?",
    "options": ["4", "22", "2+2", "Error"],
    "correctOption": 1,
    "explanation": "The + operator with a String performs string concatenation. 2 + \"2\" = \"22\"."
  },
  {
    "testId": "java-test-01",
    "question": "What is the default value of a `String` reference in Java?",
    "options": ["\"\"", "null", "undefined", "default"],
    "correctOption": 1,
    "explanation": "Reference types default to `null` if not explicitly initialized."
  },
  {
    "testId": "java-test-01",
    "question": "What is the main difference between `==` and `.equals()` in Java?",
    "options": [
      "== compares references; .equals() compares content",
      ".equals() compares references; == compares content",
      "Both compare references",
      "Both compare content"
    ],
    "correctOption": 0,
    "explanation": "For objects, `==` checks if both variables refer to the same object. `.equals()` compares the content (overridden by classes like String)."
  },
  {
    "testId": "java-test-01",
    "question": "Which of the following is a valid Java comment?",
    "options": ["// comment", "/* comment */", "/** comment */", "All of the above"],
    "correctOption": 3,
    "explanation": "Java supports single-line (//), multi-line (/* */), and Javadoc (/** */) comments."
  },
  {
    "testId": "java-test-01",
    "question": "What is the Java source file name extension?",
    "options": [".class", ".java", ".jav", ".j"],
    "correctOption": 1,
    "explanation": "Java source files have the `.java` extension. Compiled bytecode files have the `.class` extension."
  },
  {
    "testId": "java-test-01",
    "question": "What does the `static` keyword mean?",
    "options": [
      "The member belongs to the class, not the instance",
      "The member belongs to an instance",
      "The member cannot be changed",
      "The member is private"
    ],
    "correctOption": 0,
    "explanation": "Static members belong to the class level, shared across all instances."
  },
  {
    "testId": "java-test-01",
    "question": "What is the size of a `char` in Java?",
    "options": ["8 bits", "16 bits", "32 bits", "64 bits"],
    "correctOption": 1,
    "explanation": "In Java, `char` is a 16-bit Unicode character, ranging from 0 to 65,535."
  },
  {
    "testId": "java-test-01",
    "question": "What is the purpose of the `this` keyword?",
    "options": [
      "To refer to the current object instance",
      "To refer to the parent class",
      "To refer to a static variable",
      "To call a superclass method"
    ],
    "correctOption": 0,
    "explanation": "`this` refers to the current object instance, used to differentiate instance variables from parameters."
  },
  {
    "testId": "java-test-01",
    "question": "Which of the following is NOT a valid access modifier in Java?",
    "options": ["public", "private", "protected", "internal"],
    "correctOption": 3,
    "explanation": "Java has public, private, protected, and default (package-private) access modifiers. 'internal' is not a Java keyword."
  },
  {
    "testId": "java-test-01",
    "question": "What is the output of `System.out.println(5 % 2)`?",
    "options": ["1", "2", "2.5", "0"],
    "correctOption": 0,
    "explanation": "The modulus operator (%) returns the remainder of division. 5 % 2 = 1."
  },
  {
    "testId": "java-test-01",
    "question": "Which of the following is a valid way to create an array in Java?",
    "options": ["int[] arr = new int[5];", "int arr[] = new int[5];", "int arr[5];", "Both A and B"],
    "correctOption": 3,
    "explanation": "Both `int[] arr` and `int arr[]` are valid syntax for declaring arrays in Java."
  },
  {
    "testId": "java-test-01",
    "question": "What is the purpose of the `new` keyword?",
    "options": [
      "To create a new object instance",
      "To create a new variable",
      "To import a package",
      "To define a new class"
    ],
    "correctOption": 0,
    "explanation": "The `new` keyword is used to instantiate objects and allocate memory."
  },
  {
    "testId": "java-test-01",
    "question": "What is the output of `System.out.println(true || false)`?",
    "options": ["true", "false", "0", "1"],
    "correctOption": 0,
    "explanation": "The logical OR operator (`||`) returns true if at least one operand is true."
  },
  {
    "testId": "java-test-01",
    "question": "What does the `super` keyword do?",
    "options": [
      "Refers to the immediate parent class",
      "Refers to the current class",
      "Refers to a static method",
      "Refers to the current object"
    ],
    "correctOption": 0,
    "explanation": "`super` is used to refer to the immediate parent class, often used in constructors and method overrides."
  },
  {
    "testId": "java-test-01",
    "question": "What is the main difference between a `while` loop and a `do-while` loop?",
    "options": [
      "do-while executes the body at least once; while checks condition first",
      "while executes at least once; do-while checks condition first",
      "Both execute at least once",
      "Both check condition first"
    ],
    "correctOption": 0,
    "explanation": "The `do-while` loop executes the body first then checks the condition, guaranteeing at least one execution."
  },
  {
    "testId": "java-test-02",
    "question": "What is encapsulation in OOP?",
    "options": [
      "Bundling data and methods that operate on the data within a class",
      "Inheriting from a superclass",
      "Using multiple methods with the same name",
      "Creating multiple instances of a class"
    ],
    "correctOption": 0,
    "explanation": "Encapsulation bundles data and methods within a class, hiding implementation details and exposing a controlled interface."
  },
  {
    "testId": "java-test-02",
    "question": "Which keyword is used to inherit from a class?",
    "options": ["extends", "implements", "inherits", "new"],
    "correctOption": 0,
    "explanation": "The `extends` keyword is used for class inheritance. `implements` is used for interfaces."
  },
  {
    "testId": "java-test-02",
    "question": "What is polymorphism in Java?",
    "options": [
      "The ability to take many forms, allowing one interface to be used for different data types",
      "The ability to create multiple instances of a class",
      "The ability to inherit from multiple classes",
      "The ability to encapsulate data"
    ],
    "correctOption": 0,
    "explanation": "Polymorphism allows objects of different classes to be treated as objects of a common superclass, with method overriding."
  },
  {
    "testId": "java-test-02",
    "question": "What is the difference between an abstract class and an interface?",
    "options": [
      "Abstract class can have instance variables; interface only constants",
      "Abstract class can have constructors; interface cannot",
      "Abstract class can have concrete methods; interface cannot (before Java 8)",
      "All of the above"
    ],
    "correctOption": 3,
    "explanation": "Abstract classes can have instance variables, constructors, and concrete methods. Interfaces traditionally had only abstract methods until Java 8 introduced default and static methods."
  },
  {
    "testId": "java-test-02",
    "question": "Which keyword is used to define an interface in Java?",
    "options": ["interface", "abstract", "implements", "extends"],
    "correctOption": 0,
    "explanation": "The `interface` keyword is used to define an interface. `implements` is used to implement it."
  },
  {
    "testId": "java-test-02",
    "question": "What is method overloading?",
    "options": [
      "Multiple methods with the same name but different parameters",
      "Multiple methods with the same name and same parameters",
      "A method that overrides a superclass method",
      "A method that uses the same name as the class"
    ],
    "correctOption": 0,
    "explanation": "Method overloading allows multiple methods with the same name but different parameter lists in the same class."
  },
  {
    "testId": "java-test-02",
    "question": "What is method overriding?",
    "options": [
      "A subclass providing a specific implementation of a superclass method",
      "Multiple methods with the same name but different parameters",
      "A method that is called when an object is created",
      "A method that is static"
    ],
    "correctOption": 0,
    "explanation": "Method overriding allows a subclass to provide a specific implementation of a method defined in its superclass."
  },
  {
    "testId": "java-test-02",
    "question": "Which of the following is NOT an OOP principle?",
    "options": ["Encapsulation", "Inheritance", "Polymorphism", "Compilation"],
    "correctOption": 3,
    "explanation": "The four main OOP principles are Encapsulation, Inheritance, Polymorphism, and Abstraction. Compilation is not an OOP principle."
  },
  {
    "testId": "java-test-02",
    "question": "What is the purpose of a constructor?",
    "options": [
      "To initialize an object when it is created",
      "To destroy an object",
      "To call a method",
      "To define a class"
    ],
    "correctOption": 0,
    "explanation": "A constructor is a special method that initializes the state of an object when it is instantiated."
  },
  {
    "testId": "java-test-02",
    "question": "What is the default constructor in Java?",
    "options": [
      "A constructor with no parameters provided by the compiler",
      "A constructor that takes no parameters and is always explicit",
      "A constructor that is called automatically by the JVM",
      "A constructor that has zero lines of code"
    ],
    "correctOption": 0,
    "explanation": "If no constructor is defined, the Java compiler automatically provides a default constructor with no parameters."
  },
  {
    "testId": "java-test-02",
    "question": "Which of the following is true about the `super()` call?",
    "options": [
      "It must be the first statement in the constructor",
      "It can be called anywhere in the constructor",
      "It is optional in all constructors",
      "It can only be called in the child class constructor"
    ],
    "correctOption": 0,
    "explanation": "`super()` must be the first statement in a constructor to initialize the parent class properly."
  },
  {
    "testId": "java-test-02",
    "question": "What is the difference between `final` and `abstract` classes?",
    "options": [
      "A final class cannot be extended; an abstract class must be extended",
      "A final class must be extended; an abstract class cannot be extended",
      "Both cannot be extended",
      "Both must be extended"
    ],
    "correctOption": 0,
    "explanation": "A `final` class cannot be inherited from. An `abstract` class cannot be instantiated and is designed to be extended."
  },
  {
    "testId": "java-test-02",
    "question": "Which of the following is a valid way to instantiate an object?",
    "options": ["new ClassName()", "ClassName.newInstance()", "new ClassName", "ClassName()"],
    "correctOption": 0,
    "explanation": "Objects are instantiated using the `new` keyword followed by the constructor call."
  },
  {
    "testId": "java-test-03",
    "question": "Which of the following is a primitive data type in Java?",
    "options": ["int", "Integer", "String", "Object"],
    "correctOption": 0,
    "explanation": "Primitive types include int, byte, short, long, float, double, char, and boolean. Integer, String, and Object are reference types."
  },
  {
    "testId": "java-test-03",
    "question": "What is the output of `int x = 5; System.out.println(x++);`?",
    "options": ["5", "6", "0", "Error"],
    "correctOption": 0,
    "explanation": "Post-increment (`x++`) returns the current value (5) then increments x to 6."
  },
  {
    "testId": "java-test-03",
    "question": "What does the `instanceof` operator do?",
    "options": [
      "Checks if an object is an instance of a specific class or interface",
      "Checks if two objects are equal",
      "Checks if a variable is null",
      "Checks if a class is abstract"
    ],
    "correctOption": 0,
    "explanation": "The `instanceof` operator tests whether an object is an instance of a particular class or interface."
  },
  {
    "testId": "java-test-03",
    "question": "What is the difference between `&&` and `&`?",
    "options": [
      "&& is short-circuit; & evaluates both operands",
      "& is short-circuit; && evaluates both operands",
      "Both are short-circuit",
      "Both evaluate both operands"
    ],
    "correctOption": 0,
    "explanation": "`&&` (short-circuit AND) stops if the first condition is false. `&` evaluates both operands regardless."
  },
  {
    "testId": "java-test-03",
    "question": "What is the default value of a `byte` variable in Java?",
    "options": ["0", "1", "-1", "null"],
    "correctOption": 0,
    "explanation": "The default value for a byte is 0. For numeric types, default is 0; for char, '\u0000'."
  },
  {
    "testId": "java-test-03",
    "question": "What is the size of a `long` data type?",
    "options": ["32 bits", "64 bits", "128 bits", "16 bits"],
    "correctOption": 1,
    "explanation": "A `long` is a 64-bit signed integer in Java."
  },
  {
    "testId": "java-test-03",
    "question": "Which operator is used for type casting?",
    "options": ["(type)", "type()", "cast type", "::"],
    "correctOption": 0,
    "explanation": "Type casting uses the syntax `(type) variable` to convert one data type to another."
  },
  {
    "testId": "java-test-03",
    "question": "What is the output of `System.out.println(1 + 2 + \"3\")`?",
    "options": ["33", "123", "6", "1+23"],
    "correctOption": 0,
    "explanation": "Operations proceed left to right: 1+2=3, then 3+\"3\" = \"33\" (string concatenation)."
  },
  {
    "testId": "java-test-03",
    "question": "What does the `+=` operator do?",
    "options": [
      "Adds and assigns the value to the variable",
      "Checks equality",
      "Compares two values",
      "Assigns a value only"
    ],
    "correctOption": 0,
    "explanation": "`x += 5` is a compound assignment operator equivalent to `x = x + 5`."
  },
  {
    "testId": "java-test-03",
    "question": "What is the default value of a `float` variable?",
    "options": ["0.0f", "0.0", "null", "0"],
    "correctOption": 0,
    "explanation": "The default value for a float is 0.0f (or 0.0)."
  },
  {
    "testId": "java-test-03",
    "question": "Which of the following is a valid expression?",
    "options": ["5 > 3", "\"Hello\" + 5", "true && false", "All of the above"],
    "correctOption": 3,
    "explanation": "All are valid Java expressions: relational, concatenation, and logical operations."
  },
  {
    "testId": "java-test-03",
    "question": "What is the purpose of the `strictfp` keyword?",
    "options": [
      "To ensure floating-point calculations are platform-independent",
      "To make a class final",
      "To make a method static",
      "To handle exceptions"
    ],
    "correctOption": 0,
    "explanation": "`strictfp` restricts floating-point calculations to ensure portability across platforms."
  },
  {
    "testId": "java-test-04",
    "question": "Is a String in Java mutable or immutable?",
    "options": ["Immutable", "Mutable", "Partially mutable", "Depends on the version"],
    "correctOption": 0,
    "explanation": "String objects are immutable in Java, meaning their state cannot be changed after creation."
  },
  {
    "testId": "java-test-04",
    "question": "Which class is used for mutable strings?",
    "options": ["String", "StringBuffer", "StringBuilder", "Both B and C"],
    "correctOption": 3,
    "explanation": "Both StringBuffer (thread-safe) and StringBuilder (not thread-safe) are mutable string classes."
  },
  {
    "testId": "java-test-04",
    "question": "What is the difference between ArrayList and LinkedList?",
    "options": [
      "ArrayList uses dynamic array; LinkedList uses doubly linked list",
      "LinkedList uses array; ArrayList uses linked list",
      "Both use arrays",
      "Both use linked lists"
    ],
    "correctOption": 0,
    "explanation": "ArrayList is backed by a dynamic array (fast random access), while LinkedList is backed by a doubly linked list (fast insertions/deletions)."
  },
  {
    "testId": "java-test-04",
    "question": "Which collection class does NOT allow duplicate elements?",
    "options": ["ArrayList", "HashSet", "LinkedList", "HashMap"],
    "correctOption": 1,
    "explanation": "HashSet (and Set interface) does not allow duplicate elements. ArrayList and LinkedList allow duplicates."
  },
  {
    "testId": "java-test-04",
    "question": "What is the difference between HashMap and Hashtable?",
    "options": [
      "HashMap is not synchronized; Hashtable is synchronized",
      "Hashtable allows null keys; HashMap does not",
      "HashMap is synchronized; Hashtable is not",
      "Both allow null keys"
    ],
    "correctOption": 0,
    "explanation": "HashMap is not synchronized and allows one null key. Hashtable is synchronized and does not allow null keys."
  },
  {
    "testId": "java-test-04",
    "question": "What is the default initial capacity of an ArrayList?",
    "options": ["10", "16", "8", "32"],
    "correctOption": 0,
    "explanation": "The default initial capacity of an ArrayList is 10 elements."
  },
  {
    "testId": "java-test-04",
    "question": "Which method is used to convert a String to a char array?",
    "options": ["toCharArray()", "getChars()", "chars()", "toArray()"],
    "correctOption": 0,
    "explanation": "`String.toCharArray()` converts a string to a char array."
  },
  {
    "testId": "java-test-04",
    "question": "What is the difference between `StringBuffer` and `StringBuilder`?",
    "options": [
      "StringBuffer is thread-safe; StringBuilder is not",
      "StringBuilder is thread-safe; StringBuffer is not",
      "Both are thread-safe",
      "Both are not thread-safe"
    ],
    "correctOption": 0,
    "explanation": "StringBuffer's methods are synchronized (thread-safe), while StringBuilder is not synchronized but faster."
  },
  {
    "testId": "java-test-04",
    "question": "Which collection implementation maintains elements in sorted order?",
    "options": ["HashSet", "TreeSet", "ArrayList", "HashMap"],
    "correctOption": 1,
    "explanation": "TreeSet maintains elements in sorted order (natural or custom comparator)."
  },
  {
    "testId": "java-test-04",
    "question": "What is the result of `\"Hello\".concat(\"World\")`?",
    "options": ["HelloWorld", "Hello World", "Hello+World", "Error"],
    "correctOption": 0,
    "explanation": "`concat()` joins the two strings without adding a space."
  },
  {
    "testId": "java-test-04",
    "question": "What is the output of `System.out.println(\"abc\".substring(1, 3))`?",
    "options": ["bc", "abc", "ab", "b"],
    "correctOption": 0,
    "explanation": "`substring(1, 3)` returns characters from index 1 to 2 (3 is exclusive). 'b'(1) + 'c'(2) = \"bc\"."
  },
  {
    "testId": "java-test-04",
    "question": "Which collection is used to store key-value pairs?",
    "options": ["Set", "List", "Queue", "Map"],
    "correctOption": 3,
    "explanation": "The Map interface (e.g., HashMap, TreeMap) stores key-value pairs."
  },
  {
    "testId": "java-test-04",
    "question": "What is the purpose of the `equals()` method in collections?",
    "options": [
      "To compare two objects for equality",
      "To compare two objects for identity",
      "To hash the object",
      "To clone the object"
    ],
    "correctOption": 0,
    "explanation": "`equals()` is used to compare the content of two objects for equality, commonly used in collections."
  },
  {
    "testId": "java-test-04",
    "question": "Which method is used to add an element to a HashSet?",
    "options": ["add()", "put()", "insert()", "append()"],
    "correctOption": 0,
    "explanation": "The `add()` method is used to add elements to a HashSet."
  },
  {
    "testId": "java-test-04",
    "question": "Which interface does ArrayList implement?",
    "options": ["List", "Set", "Map", "Queue"],
    "correctOption": 0,
    "explanation": "ArrayList implements the List interface, among others."
  },
  {
    "testId": "java-test-05",
    "question": "What is the difference between checked and unchecked exceptions?",
    "options": [
      "Checked exceptions are checked at compile-time; unchecked at runtime",
      "Unchecked are checked at compile-time; checked at runtime",
      "Both are checked at compile-time",
      "Both are checked at runtime"
    ],
    "correctOption": 0,
    "explanation": "Checked exceptions (e.g., IOException) are checked by the compiler; unchecked exceptions (e.g., NullPointerException) occur at runtime."
  },
  {
    "testId": "java-test-05",
    "question": "Which keyword is used to manually throw an exception?",
    "options": ["throw", "throws", "try", "catch"],
    "correctOption": 0,
    "explanation": "The `throw` keyword is used to explicitly throw an exception. `throws` is used in method declarations."
  },
  {
    "testId": "java-test-05",
    "question": "What is the purpose of the `finally` block?",
    "options": [
      "To execute code regardless of whether an exception occurs",
      "To catch exceptions",
      "To throw exceptions",
      "To define a custom exception"
    ],
    "correctOption": 0,
    "explanation": "The `finally` block always executes, whether an exception occurs or not, typically used for cleanup."
  },
  {
    "testId": "java-test-05",
    "question": "What is a `try-with-resources` statement?",
    "options": [
      "Automatically closes resources that implement AutoCloseable",
      "A try block that catches resources",
      "A block that declares resources",
      "A block that throws resources"
    ],
    "correctOption": 0,
    "explanation": "Try-with-resources automatically closes resources (like files, database connections) that implement AutoCloseable."
  },
  {
    "testId": "java-test-05",
    "question": "Which of the following is a checked exception?",
    "options": ["NullPointerException", "ArithmeticException", "IOException", "ArrayIndexOutOfBoundsException"],
    "correctOption": 2,
    "explanation": "IOException is a checked exception. The others are unchecked (RuntimeException subclasses)."
  },
  {
    "testId": "java-test-05",
    "question": "What is the purpose of the `throws` keyword?",
    "options": [
      "To declare that a method may throw an exception",
      "To throw an exception",
      "To catch an exception",
      "To handle an exception"
    ],
    "correctOption": 0,
    "explanation": "The `throws` keyword in a method signature declares that the method may throw certain exceptions."
  },
  {
    "testId": "java-test-05",
    "question": "What is the output of the following code?\n```java\ntry {\n    int x = 10 / 0;\n} catch (Exception e) {\n    System.out.println(\"Exception\");\n} catch (ArithmeticException e) {\n    System.out.println(\"Arithmetic\");\n}\n```",
    "options": ["Exception", "Arithmetic", "Error", "Compilation error"],
    "correctOption": 3,
    "explanation": "This code will not compile because ArithmeticException is a subclass of Exception, so the first catch block (Exception) would catch it before the second block."
  },
  {
    "testId": "java-test-05",
    "question": "Which class is the superclass of all exceptions?",
    "options": ["Exception", "RuntimeException", "Throwable", "Error"],
    "correctOption": 2,
    "explanation": "The root class for all exceptions is `Throwable`, which has two subclasses: Exception and Error."
  },
  {
    "testId": "java-test-05",
    "question": "How do you create a custom exception?",
    "options": [
      "Extend the Exception class",
      "Implement the Throwable interface",
      "Extend the RuntimeException class",
      "Both A and C are valid"
    ],
    "correctOption": 3,
    "explanation": "Custom exceptions can extend either Exception (checked) or RuntimeException (unchecked)."
  },
  {
    "testId": "java-test-05",
    "question": "What is the purpose of the `Scanner` class?",
    "options": [
      "To read user input from the console",
      "To write to files",
      "To handle exceptions",
      "To read from databases"
    ],
    "correctOption": 0,
    "explanation": "The Scanner class is used to read primitive types and strings from the console or files."
  },
  {
    "testId": "java-test-05",
    "question": "Which class is used for reading text files efficiently?",
    "options": ["BufferedReader", "FileReader", "Scanner", "All of the above"],
    "correctOption": 3,
    "explanation": "All can read text files, but BufferedReader is the most efficient for large files."
  },
  {
    "testId": "java-test-06",
    "question": "What is a thread in Java?",
    "options": [
      "A lightweight process that runs concurrently with others",
      "A method that runs sequentially",
      "A class that handles exceptions",
      "A type of memory management"
    ],
    "correctOption": 0,
    "explanation": "A thread is the smallest unit of execution that can run concurrently with other threads within a process."
  },
  {
    "testId": "java-test-06",
    "question": "Which two ways can you create a thread in Java?",
    "options": [
      "Extending Thread class or implementing Runnable interface",
      "Extending Runnable or implementing Thread",
      "Only extending Thread",
      "Only implementing Runnable"
    ],
    "correctOption": 0,
    "explanation": "Threads can be created by extending the Thread class or implementing the Runnable interface."
  },
  {
    "testId": "java-test-06",
    "question": "What is the purpose of the `synchronized` keyword?",
    "options": [
      "To ensure only one thread can access the resource at a time",
      "To make a method faster",
      "To handle exceptions",
      "To create new threads"
    ],
    "correctOption": 0,
    "explanation": "The `synchronized` keyword ensures mutual exclusion, allowing only one thread to access a block or method at a time."
  },
  {
    "testId": "java-test-06",
    "question": "What is a deadlock in multithreading?",
    "options": [
      "When two or more threads are waiting for each other to release resources",
      "When a thread terminates unexpectedly",
      "When a thread runs indefinitely",
      "When a thread is blocked by I/O"
    ],
    "correctOption": 0,
    "explanation": "Deadlock occurs when two or more threads are blocked forever, each waiting for the other to release a resource."
  },
  {
    "testId": "java-test-06",
    "question": "What are the states in a thread's lifecycle?",
    "options": [
      "New, Runnable, Blocked, Waiting, Timed Waiting, Terminated",
      "New, Running, Sleeping, Dead",
      "Created, Ready, Running, Dead",
      "Start, Run, Stop, Pause"
    ],
    "correctOption": 0,
    "explanation": "The thread lifecycle states are New, Runnable, Blocked, Waiting, Timed Waiting, and Terminated."
  },
  {
    "testId": "java-test-06",
    "question": "What is the `wait()` method used for?",
    "options": [
      "To make a thread release the lock and enter the waiting state",
      "To make a thread sleep",
      "To stop a thread",
      "To notify another thread"
    ],
    "correctOption": 0,
    "explanation": "`wait()` releases the lock and causes the current thread to wait until another thread calls `notify()` or `notifyAll()`."
  },
  {
    "testId": "java-test-06",
    "question": "What is the difference between `sleep()` and `wait()`?",
    "options": [
      "sleep() does not release the lock; wait() releases the lock",
      "wait() does not release the lock; sleep() releases the lock",
      "Both release the lock",
      "Neither releases the lock"
    ],
    "correctOption": 0,
    "explanation": "`sleep()` keeps the lock while sleeping. `wait()` releases the lock and waits for notification."
  },
  {
    "testId": "java-test-06",
    "question": "What is an `ExecutorService` in Java?",
    "options": [
      "A framework for managing and controlling threads",
      "A class for executing tasks sequentially",
      "A type of thread",
      "A synchronized collection"
    ],
    "correctOption": 0,
    "explanation": "ExecutorService is a framework for managing thread pools and executing asynchronous tasks efficiently."
  },
  {
    "testId": "java-test-06",
    "question": "Which method is used to shut down an ExecutorService?",
    "options": ["shutdown()", "shutdownNow()", "Both A and B", "stop()"],
    "correctOption": 2,
    "explanation": "`shutdown()` initiates a graceful shutdown; `shutdownNow()` attempts an immediate shutdown."
  },
  {
    "testId": "java-test-06",
    "question": "What is a `Callable` in Java?",
    "options": [
      "A task that can return a result and throw an exception",
      "A task that does not return a result",
      "A type of thread",
      "A synchronized block"
    ],
    "correctOption": 0,
    "explanation": "Callable is similar to Runnable but can return a value and throw checked exceptions."
  },
  {
    "testId": "java-test-06",
    "question": "What is the purpose of `volatile` keyword?",
    "options": [
      "To ensure variable changes are visible to all threads",
      "To make a variable read-only",
      "To make a variable immutable",
      "To synchronize a variable"
    ],
    "correctOption": 0,
    "explanation": "`volatile` ensures that writes to a variable are immediately visible to all threads."
  },
  {
    "testId": "java-test-07",
    "question": "What is a lambda expression in Java?",
    "options": [
      "An anonymous function that can be passed as a parameter",
      "A class that implements an interface",
      "A method that returns a value",
      "A type of variable"
    ],
    "correctOption": 0,
    "explanation": "Lambda expressions are anonymous functions used to implement functional interfaces concisely."
  },
  {
    "testId": "java-test-07",
    "question": "Which symbol is used in a lambda expression?",
    "options": ["->", "=>", "::", "--"],
    "correctOption": 0,
    "explanation": "Lambda expressions use the arrow operator `->` to separate parameters from the body."
  },
  {
    "testId": "java-test-07",
    "question": "What is a functional interface?",
    "options": [
      "An interface with exactly one abstract method",
      "An interface with multiple abstract methods",
      "A class that implements an interface",
      "An interface with only default methods"
    ],
    "correctOption": 0,
    "explanation": "A functional interface has exactly one abstract method and can be implemented using a lambda expression."
  },
  {
    "testId": "java-test-07",
    "question": "Which of the following is a functional interface?",
    "options": ["Runnable", "Comparator", "Callable", "All of the above"],
    "correctOption": 3,
    "explanation": "Runnable, Comparator, and Callable are all functional interfaces with a single abstract method."
  },
  {
    "testId": "java-test-07",
    "question": "What is the purpose of the `@FunctionalInterface` annotation?",
    "options": [
      "To indicate the interface is a functional interface",
      "To make an interface abstract",
      "To make a method static",
      "To define default methods"
    ],
    "correctOption": 0,
    "explanation": "`@FunctionalInterface` marks an interface as functional, and the compiler will enforce the single abstract method rule."
  },
  {
    "testId": "java-test-07",
    "question": "What is a method reference in Java?",
    "options": [
      "A shorthand notation for lambda expressions using `::`",
      "A method that references another method",
      "A method that is static",
      "A method that returns a value"
    ],
    "correctOption": 0,
    "explanation": "Method references (`::`) are a compact way to refer to existing methods, used in place of lambda expressions."
  },
  {
    "testId": "java-test-07",
    "question": "What are the four types of method references?",
    "options": [
      "Static, Instance, Constructor, Super",
      "Static, Instance, Class, Constructor",
      "Static, Instance, Abstract, Constructor",
      "Static, Final, Constructor, Private"
    ],
    "correctOption": 0,
    "explanation": "The four types are: static method reference, instance method reference, constructor reference, and super method reference."
  },
  {
    "testId": "java-test-07",
    "question": "Which Stream API operation is used to transform each element?",
    "options": ["map()", "filter()", "reduce()", "forEach()"],
    "correctOption": 0,
    "explanation": "`map()` applies a function to each element and returns a new stream of transformed elements."
  },
  {
    "testId": "java-test-07",
    "question": "Which Stream operation filters elements based on a condition?",
    "options": ["filter()", "map()", "reduce()", "collect()"],
    "correctOption": 0,
    "explanation": "`filter()` returns a new stream containing only elements that satisfy the given predicate."
  },
  {
    "testId": "java-test-07",
    "question": "What is the difference between `map()` and `flatMap()`?",
    "options": [
      "map() returns a stream of elements; flatMap() flattens nested streams",
      "flatMap() returns a stream; map() flattens",
      "Both are the same",
      "map() is for collections; flatMap() is for arrays"
    ],
    "correctOption": 0,
    "explanation": "`map()` applies a function that returns a value; `flatMap()` applies a function that returns a stream and flattens the result."
  },
  {
    "testId": "java-test-07",
    "question": "What is the purpose of `Optional` in Java?",
    "options": [
      "To avoid NullPointerException by representing null-safe values",
      "To handle exceptions",
      "To replace all null values",
      "To create new objects"
    ],
    "correctOption": 0,
    "explanation": "Optional is a container object that may or may not contain a non-null value, helping to avoid NullPointerExceptions."
  },
  {
    "testId": "java-test-08",
    "question": "What are generics in Java?",
    "options": [
      "Type safety mechanism that allows classes to operate on different types",
      "A generic class that can be instantiated",
      "A type of collection",
      "A type of interface"
    ],
    "correctOption": 0,
    "explanation": "Generics enable classes, interfaces, and methods to operate on parameterized types, providing compile-time type safety."
  },
  {
    "testId": "java-test-08",
    "question": "What is the purpose of the `@Override` annotation?",
    "options": [
      "To indicate a method is overriding a superclass method",
      "To indicate a method is abstract",
      "To make a method final",
      "To mark a method as deprecated"
    ],
    "correctOption": 0,
    "explanation": "`@Override` tells the compiler that the annotated method is intended to override a method from the superclass."
  },
  {
    "testId": "java-test-08",
    "question": "What is an annotation in Java?",
    "options": [
      "Metadata that provides additional information about the code",
      "A type of class",
      "A type of variable",
      "A type of method"
    ],
    "correctOption": 0,
    "explanation": "Annotations are metadata that can be added to code to provide information to the compiler, runtime, or tools."
  },
  {
    "testId": "java-test-08",
    "question": "What is a vararg in Java?",
    "options": [
      "A method that can accept a variable number of arguments",
      "A variable that can change type",
      "A variable that is final",
      "A variable that is static"
    ],
    "correctOption": 0,
    "explanation": "Varargs (variable arguments) allow a method to accept zero or more arguments of the same type."
  },
  {
    "testId": "java-test-08",
    "question": "What is the purpose of the `try-with-resources` statement?",
    "options": [
      "To automatically close resources that implement AutoCloseable",
      "To catch exceptions",
      "To throw exceptions",
      "To define multiple catch blocks"
    ],
    "correctOption": 0,
    "explanation": "Try-with-resources is a shorthand for declaring and automatically closing resources at the end of the try block."
  },
  {
    "testId": "java-test-08",
    "question": "What is an enum in Java?",
    "options": [
      "A special type of class that represents a fixed set of constants",
      "A type of interface",
      "A type of annotation",
      "A type of method"
    ],
    "correctOption": 0,
    "explanation": "An enum defines a fixed set of constants, providing type safety and methods like values() and ordinal()."
  },
  {
    "testId": "java-test-08",
    "question": "What is the purpose of a Java module (Java 9+)?",
    "options": [
      "To group related packages and control access",
      "To create new classes",
      "To define interfaces",
      "To handle exceptions"
    ],
    "correctOption": 0,
    "explanation": "Modules provide encapsulation at a higher level, allowing a module to control which packages are exposed to other modules."
  },
  {
    "testId": "java-test-08",
    "question": "What is a record in Java (Java 14+)?",
    "options": [
      "A data carrier class that automatically provides equals, hashCode, and toString",
      "A type of interface",
      "A type of annotation",
      "A type of enum"
    ],
    "correctOption": 0,
    "explanation": "Records are transparent data carriers that reduce boilerplate by automatically generating common methods."
  },
  {
    "testId": "java-test-08",
    "question": "What is the purpose of `java.util.logging`?",
    "options": [
      "To provide logging capabilities",
      "To handle exceptions",
      "To manage threads",
      "To read input"
    ],
    "correctOption": 0,
    "explanation": "`java.util.logging` provides a built-in logging framework for Java applications."
  },
  {
    "testId": "java-test-08",
    "question": "Which of the following is NOT a valid access modifier for a top-level class?",
    "options": ["public", "private", "default (no modifier)", "abstract"],
    "correctOption": 1,
    "explanation": "Top-level classes cannot be private. They can be public or package-private (default)."
  },
  {
    "testId": "java-test-08",
    "question": "What is garbage collection in Java?",
    "options": [
      "Automatic memory management to free unused objects",
      "Manual memory management",
      "A type of exception",
      "A type of thread"
    ],
    "correctOption": 0,
    "explanation": "Garbage collection is Java's automatic memory management system that frees memory occupied by unreachable objects."
  }
];

let questionsFile = fs.readFileSync('src/data/questions.js', 'utf8');
const endBraceIndex = questionsFile.lastIndexOf('];');

if (endBraceIndex !== -1 && !questionsFile.includes('"java-test-01"')) {
  const injectionString = ',\n' + questions.map(q => JSON.stringify(q, null, 2)).join(',\n') + '\n];';
  questionsFile = questionsFile.substring(0, endBraceIndex) + injectionString;
  fs.writeFileSync('src/data/questions.js', questionsFile);
  console.log('Successfully injected java questions into questions.js array!');
} else {
  console.log('Questions already exist or questions.js is not an array ending in ];');
}
